#!/usr/bin/perl -w
# $Id: mkversion,v 1.1.1.1 2010-02-01 20:58:03 grahn Exp $
# $Name:  $
#
# Copyright (c) 2010 Jörgen Grahn
# All rights reserved.

use strict;
use Getopt::Std;

my $usage = "usage: $0 name version file\n";
getopts('') or die $usage;
$#ARGV==2 or die $usage;

my ($name, $version, $file) = @ARGV;

my ($oname, $oversion) = ('', '');

if(open FD, "<$file") {

    while(<FD>) {
	$oname = $1 if /\bname\b.+?return \"(.+?)\"/;
	$oversion = $1 if /\bversion\b.+?return \"(.+?)\"/;
    }
    close FD or die;
}

exit 0 if $name eq $oname && $version eq $oversion;

open FD, ">$file" or die "cannot open '$file' for writing: $!\n";
print FD "const char* name(void) { return \"$name\"; }\n";
print FD "const char* version(void) { return \"$version\"; }\n";
close FD or die;

exit 0;
