.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.ds rt90 \s-1RT90\s0
.ds sweref99 \s-1SWEREF\ 99\s0
.
.
.
.TH rt90 1 "JUN 2012" "RT90" "User Manuals"
.
.SH "NAME"
rt90 \- coordinate conversion between RT90 and SWEREF99
.
.SH "SYNOPSIS"
.
.B rt90
.RI [ \-N ]
.RI [ "north east" ]
.
.br
.B rt90
.RB [ --from
|
.BR --to ]
.RI [ \-N ]
.RI [ "north east" ]
.
.br
.B rt90
.B --test
.br
.B rt90
.B --version
.br
.B rt90
.B --help
.
.SH "DESCRIPTION"
.
.B rt90
is a small utility for safely converting between
the coordinate systems (or whatever the proper term is)
.B "\s-1RT90\s0\ 2.5\ gon\ V"
and
.BR "\s-1SWEREF\ 99\ TM\s0" .
\*[rt90] is the most popular coordinate system for use
in Sweden; \*[sweref99] is the new standard we're switching to.
Both assign a north and an east coordinate,
expressed in meters,
to every spot in the country (and some spots
.I outside
it, I'm sure).
.
.
.SS "Coordinate format"
Coordinates may be given on the command line, or as standard input.
.BR "On the command line" ,
it's just two numerical arguments \- north and east.
.BR "On standard input" ,
any line which is just two suitably large
numbers (separated by whitespace) is processed as a coordinate and translated.
Other lines are passed straight through.
.PP
\*[sweref99] coordinates are always seven digits northing and six digits easting,
e.g. 7454204\ 761811.
.PP
For \*[rt90] coordinates, the typical format is seven digits northing and
seven digits easting, e.g.
\s-264\s052109\ \s-213\s068036 .
This is with 1\ m resolution.
There are also shorter forms with 10\ m, 100\ m and 1\ km resolution:
\s-264\s05211\ \s-213\s06804,
\s-264\s0521\ \s-213\s0680,
\s-264\s052\ \s-213\s068.
Much software today seem to only accept the full 7-digit format,
but older data is often not in 1m resolution. Some sources
use different resolutions to indicate the actual accuracy.
.PP
No matter what, a \*[rt90] coordinate cannot be mistaken for a \*[sweref99] one;
the latter always uses 7+6 digits and the former never does.
.
.
.SH "OPTIONS"
.
.BP --from
Translate only
.I "from \*[rt90]"
to \*[sweref99].
Only coordinates which are likely to be correct \*[rt90] coordinates
are translated.
.
.BP --to,\ --back
Translate only
from \*[sweref99]
.IR "to \*[rt90]" .
Only coordinates which seem like correct \*[sweref99] coordinates
are translated.
.BP
The synonym
.B --back
is supposed to be easier to remember; you're going
.I back
to an older system.
.
.PP
Without either of these options, coordinates which look like \*[rt90]
are translated to \*[sweref99], and vice versa.
.
.BP \-4,\ \-5,\ \-6,\ \-7
When translating to \*[rt90], use the 4-, 5-, 6- or 7-digit format
(rounded to 1km; 100m; 10m; 1m).
.BP
When translating
.I from
\*[rt90], only accept coordinates at this resolution.
In this case, several of them may be given;
.B \-67
will accept six- or seven-digit \*[rt90] coordinates.
.BP
Ordering is important:
.B \-67
and
.B \-76
means the same thing for \*[rt90] input,
but for \*[rt90]
.IR output ,
the latter asks for 6-digit output.
.BP
If you don't supply these, the default is
.BR \-567 :
accept 100m resolution or better; output in full 1m resolution.
.
.BP --test
Self-test, using the four reference points A\-D published by
.IR Lantm\(:ateriet .
If the deviation is more than 0.1m for either of these,
in either direction, print an error message.
.
.
.SH "EXIT STATUS"
Non-zero if the transformation clearly failed (input or would-be output doesn't
have the correct number of digits, or is widely out of range).
Also non-zero if
.B --test
fails.
.
.
.SH "FILES"
None.
.
.
.SH "ENVIRONMENT"
None.
.
.
.SH "BUGS"
.
Coordinates with decimal places (sub-meter resolution) are not accepted,
although the quality of the underlying transformations seems to
make that meaningful.
.
.PP
There are variations on both \*[rt90] and \*[sweref99] other than
\s-1RT90\s0\ 2.5\ gon\ V
and
\s-1SWEREF\ 99\ TM\s0,
better suited to different parts of the country. These are
.IR "not supported" .
I hope they are rarely relevant in situations where you'd want to use
this tool.
.
.PP
I don't own a GPS receiver.
If I understand correctly, these tend to use
.B \s-1WGS84\s0
rather than \*[sweref99].
I also understand that the difference between these two is irrelevant
to most people \-
but if it isn't irrelevant to
.IR you ,
.B rt90
is of no use.
.
.PP
I'm not an expert in this area, just someone who sometimes wants to
translate my coordinates.
The underlying tools and concepts are not easy to understand and
handle correctly, and my only indication that I haven't messed up
completely is the output from
.BR --test ,
and the unit tests supplied with the source code.
.
.
.SH "AUTHOR"
.
J\(:orgen Grahn
.IR \[fo]grahn+src@snipabacken.se\[fc] .
.PP
This is really just a wrapper script; the operation
relies entirely on
.BR libproj ,
also known as the
.B \s-1PROJ.4\s0
API, and information on \*[rt90]/\*[sweref99] gleaned from
a multitude of sources.
.
.
.SH "LICENSE"
.
The Modified BSD license.
.
.
.SH "SEE ALSO"
.
.BR cs2cs (1),
.BR proj (1),
.br
.RI \[fo] http://www.remotesensing.org/proj \[fc],
.br
.RI \[fo] http://www.lantmateriet.se \[fc].
